// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, type, account_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, type, account_id, created_at
`

type CreateCategoryParams struct {
	Name      string        `json:"name"`
	Type      string        `json:"type"`
	AccountID sql.NullInt32 `json:"account_id"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Type,
		arg.AccountID,
		arg.CreatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, type, account_id, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryIDByName = `-- name: GetCategoryIDByName :one
SELECT id FROM categories WHERE name = $1
`

func (q *Queries) GetCategoryIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoryIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, type, account_id, created_at
FROM categories
ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.AccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, type = $3, account_id = $4
WHERE id = $1
RETURNING id, name, type, account_id, created_at
`

type UpdateCategoryParams struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Type      string        `json:"type"`
	AccountID sql.NullInt32 `json:"account_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.AccountID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}
