// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: discounts.sql

package db

import (
	"context"
	"database/sql"
)

const createDiscount = `-- name: CreateDiscount :one
INSERT INTO discounts (
  discount_value,
  account_id,
  product_id
) VALUES (
  $1, $2, $3
) RETURNING id, account_id, product_id, discount_value, created_at
`

type CreateDiscountParams struct {
	DiscountValue int32         `json:"discount_value"`
	AccountID     sql.NullInt64 `json:"account_id"`
	ProductID     sql.NullInt64 `json:"product_id"`
}

func (q *Queries) CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error) {
	row := q.db.QueryRowContext(ctx, createDiscount, arg.DiscountValue, arg.AccountID, arg.ProductID)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProductID,
		&i.DiscountValue,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDiscount = `-- name: DeleteDiscount :exec
DELETE FROM discounts WHERE id = $1
`

func (q *Queries) DeleteDiscount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDiscount, id)
	return err
}

const getDiscount = `-- name: GetDiscount :one
SELECT id, account_id, product_id, discount_value, created_at FROM discounts WHERE id = $1
`

func (q *Queries) GetDiscount(ctx context.Context, id int64) (Discount, error) {
	row := q.db.QueryRowContext(ctx, getDiscount, id)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProductID,
		&i.DiscountValue,
		&i.CreatedAt,
	)
	return i, err
}

const getProductIDByAccountID = `-- name: GetProductIDByAccountID :one
SELECT product_id FROM discounts WHERE account_id = $1
`

func (q *Queries) GetProductIDByAccountID(ctx context.Context, accountID sql.NullInt64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getProductIDByAccountID, accountID)
	var product_id sql.NullInt64
	err := row.Scan(&product_id)
	return product_id, err
}

const listDiscounts = `-- name: ListDiscounts :many
SELECT id, account_id, product_id, discount_value, created_at FROM discounts ORDER BY id LIMIT $1 OFFSET $2
`

type ListDiscountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDiscounts(ctx context.Context, arg ListDiscountsParams) ([]Discount, error) {
	rows, err := q.db.QueryContext(ctx, listDiscounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discount{}
	for rows.Next() {
		var i Discount
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProductID,
			&i.DiscountValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscountsByAccountID = `-- name: ListDiscountsByAccountID :many
SELECT id, account_id, product_id, discount_value, created_at FROM discounts WHERE account_id = $1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListDiscountsByAccountIDParams struct {
	AccountID sql.NullInt64 `json:"account_id"`
	Limit     int32         `json:"limit"`
	Offset    int32         `json:"offset"`
}

func (q *Queries) ListDiscountsByAccountID(ctx context.Context, arg ListDiscountsByAccountIDParams) ([]Discount, error) {
	rows, err := q.db.QueryContext(ctx, listDiscountsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Discount{}
	for rows.Next() {
		var i Discount
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ProductID,
			&i.DiscountValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscount = `-- name: UpdateDiscount :one
UPDATE discounts
SET discount_value = $2
WHERE id = $1
RETURNING id, account_id, product_id, discount_value, created_at
`

type UpdateDiscountParams struct {
	ID            int64 `json:"id"`
	DiscountValue int32 `json:"discount_value"`
}

func (q *Queries) UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (Discount, error) {
	row := q.db.QueryRowContext(ctx, updateDiscount, arg.ID, arg.DiscountValue)
	var i Discount
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProductID,
		&i.DiscountValue,
		&i.CreatedAt,
	)
	return i, err
}
