// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// CHECK (price > 0)
	Price      int32         `json:"price"`
	CategoryID sql.NullInt32 `json:"category_id"`
	// CHECK (price >= 0)
	Value     int32     `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}
